version: '3.8'

services:
  app:
    build: .
    container_name: spring-boot-container
    networks:
      - external_network
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: urubu100
    restart: unless-stopped

networks:
  external_network:
    external: true