package school.sptech.saferide.constants;

public class ControllerConstants {
    public final static String DEPENDENTES_BASE_PATH = "/dependentes";
    public final static String DEPENDENTES_MOTORISTA_TRAJETO_BASE_PATH = "motoristas/{motoristaId}/trajetos/{trajetoId}/escolas/{escolaId}";
    public final static String ENDERECO_BASE_PATH = "/enderecos";
    public final static String ESCOLAS_BASE_PATH = "/escolas";
    public final static String CONVERSA_BASE_PATH = "/conversas";
    public final static String SOLICITACAO_BASE_PATH = "/solicitacoes";
    public final static String HISTORICO_BASE_PATH = "/historicos";
    public final static String MENSAGEM_BASE_PATH = "/mensagens";
    public final static String CONTRATO_BASE_PATH = "/contratos";
    public final static String CONTRATO_POR_MOTORISTA_BASE_PATH = "/motorista/{motoristaId}";
    public final static String CONTRATO_POR_RESPONSAVEL_BASE_PATH = "/responsavel/{responsavelId}";
    public final static String CONTRATO_POR_DEPENDENTE_BASE_PATH = "/dependente/{dependenteId}";
    public final static String PAGAMENTO_BASE_PATH = "/pagamentos";
    public final static String ROTA_BASE_PATH = "/rotas";
    public final static String TRAJETO_BASE_PATH = "/trajetos";
    public final static String TRANSPORTE_BASE_PATH = "/transportes";
    public final static String TRANSPORTE_ESCOLA_BASE_PATH = "/transportes-escolas";
    public final static String TRANSPORTE_ESCOLA_LIST_BY_TRANSPORTE_BASE_PATH = "/transporte/{transporteId}";
    public final static String TRANSPORTE_ESCOLA_LIST_BY_ESCOLA_BASE_PATH = "/escola/{escolaId}";
    public final static String USUARIO_BASE_PATH = "/usuarios";
    public final static String USUARIO_DRIVER_CLIENTS_BASE_PATH = "/clientes-motorista/{id}";
    public final static String USUARIO_DRIVER_MOTORISTA_BASE_PATH = "/motoristas/{responsavelId}";
    public final static String USUARIO_PARENT_DEPENDANTS_BASE_PATH = "/dependentes-responsavel/{id}";
    public final static String USUARIO_DRIVER_PROFILE_PATH = "/perfil-motorista/{id}";
    public final static String USUARIO_DRIVER_SCHOOL_PATH = "/motorista/escola/{idDependente}";
    public final static String DEPENDENTE_LINK_MOTORISTA_PATH = "/{dependenteId}/vincular-motorista/{motoristaId}";
    public final static String DEPENDENTE_PERFIL_BASE_PATH = "/{id}/perfil";
    public final static String SEARCH_CEP = "/buscar-cep/{cep}";
    public final static String ENDERECO_LIST_BY_USUARIO_PATH = "/usuario/{usuarioId}";
    public final static String LIST_BY_ID_PATH = "/{id}";
    public final static String REMOVE_PATH = "/{id}";
    public final static String SECURITY_NAME = "Bearer";
    public final static String LIST_STATUS_DEPENDENTE_HISTORICO = "/status-dependentes/{id}";
    public static final String USUARIO_PARENT_DRIVERS_BASE_PATH = "/motoristas-responsavel/{id}";
    public final static String CONVERSAS_RESPONSAVEL_MOTORISTAS_BASE_PATH = "/motoristas-responsavel/{id}";
    public static final String CONVERSAS_MOTORISTA_RESPONSAVEIS_BASE_PATH = "/responsaveis-motorista/{id}";
    public static final String CONTRATO_POR_MOTORISTA_E_ANO_BASE_PATH = "/motorista/{id}/ano/{ano}";
    public static final String TEMPO_REAL_BASE_PATH = "/tempo-real";
    public static final String TEMPO_REAL_CREATION_BASE_PATH = "/{motoristaId}";
    public static final String TEMPO_REAL_LAST_BASE_PATH = "/{motoristaId}";
    public static final String LIST_ENDERECOS_BY_TRAJETO = "/listar-enderecos/{idTrajeto}";
    public static final String LIST_ENDERECOS_BY_ESCOLA = "/listar-escola-endereco/{idTrajeto}";
}
