name: build-backend

on:
  push:
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin" # ver opções em https://github.com/actions/setup-java?tab=readme-ov-file#supported-distributions
          java-version: "17"

      - name: Build Maven
        run: mvn -f pom.xml clean package

      - name: Gerar artefato Github com o .jar gerado
        uses: actions/upload-artifact@v4 # essa action promove o envio de um ou mais arquivos para uma pasta temporária do github actions
        with:
          name: aplicacao # nome do arquivo ou conjunto de arquivos
          path: target/*.jar

      - name: Gerar artefato Github com os arquivos .sh
        uses: actions/upload-artifact@v4
        with:
          name: scripts # nome do arquivo ou conjunto de arquivos (veja ele depois em 'Recuperar scripts')
          path: .github/scripts/*.sh # todos os arquivos .sh do diretório .github/scripts

