name: ci-cd

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build Maven
        run: mvn -f pom.xml clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: aplicacao
          path: target/*.jar

      - name: LS
        run: ls

      - name: Upload Scripts
        uses: actions/upload-artifact@v4
        with:
          name: scripts
          path: .github/scripts/*

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Recuperar JAR
        uses: actions/download-artifact@v4
        with:
          name: aplicacao
          path: ./

      - name: Recuperar scripts
        uses: actions/download-artifact@v4
        with:
          name: scripts
          path: .github/scripts

      - name: Criar arquivo .pem
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > $HOME/${{ secrets.NOME_ARQUIVO_PEM }}
          chmod 400 $HOME/${{ secrets.NOME_ARQUIVO_PEM }}

      - name: Enviar o JAR para EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP_PRIVADO_EC2 }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./*.jar"
          target: "/home/ubuntu/"

      - name: Rodar aplicação
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IP_PRIVADO_EC2 }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            nohup sudo java -jar *.jar > /home/ubuntu/app.log 2>&1 &  

#      - name: Preparar diretório remoto na EC2
#        run: |
#          ssh -o StrictHostKeyChecking=no -i $HOME/${{ secrets.NOME_ARQUIVO_PEM }} ubuntu@${{ secrets.DEPLOY_HOST }} "mkdir -p /home/ubuntu/deploy-api && chmod 755 /home/ubuntu/deploy-api"
#
#      - name: Implantar na EC2 privada
#        run: |
#          ssh -T -o StrictHostKeyChecking=no -i $HOME/${{ secrets.NOME_ARQUIVO_PEM }} ubuntu@${{ secrets.DEPLOY_HOST }} << 'EOF'
#            echo "Implantação em andamento..."
#
#            scp -i $HOME/${{ secrets.NOME_ARQUIVO_PEM }} /home/ubuntu/deploy-api/*.jar ubuntu@${{ secrets.IP_PRIVADO_EC2 }}:/home/ubuntu/
#            echo "JAR copiado para a instância privada com sucesso."
#
#          EOF