name: saferide-backend

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build Maven
        run: mvn -f pom.xml clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: aplicacao
          path: target/*.jar

      - name: Upload Scripts
        uses: actions/upload-artifact@v3
        with:
          name: scripts
          path: .github/scripts/*.sh

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_BACKEND_USER }}
          password: ${{ secrets.DOCKERHUB_BACKEND_TOKEN }}

      - name: List files  # Opcional, para depuração
        run: ls -la

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: brunolimabh/api-backend:latest
